### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by jmercouris**
Hi Joachim, some improvements here:

+ add support for jscore/javascript return values
+ add navigation actions
+ add simple callback interface for API users

please let me know what you think!

thanks,

-John

### CODE REVIEW

**Comment by Ambrevar** [comment]
Questions:

- Why did you remove the `dom` and `soup` folders?  Can't we keep them?  @joachifm What is the purpose of those subprojects?
- @jmercouris You've removed the demo file: I think we should reintroduce it. Considering this is a rather large library, examples are welcome!

**Comment by jmercouris** [comment]
I removed DOM/SOUP folders because they were dysfunctional and incompatible with WebKit2

Demo file would be OK, I guess, but it could just as well be a section in the README I think.

**Comment by Ambrevar** [comment]
The benefit of a separate demo file is that users can run it directly
from a shell, they don't have to copy-paste it to a file.

**Comment by joachifm** [comment]
Hi, I don't have time to look at this anytime soon. I've invited you both to the repo, I'm happy to defer to your judgement re these changes. Thank you :)

**Comment by Ambrevar** [comment]
Thanks a lot!

**Comment by Ambrevar** [comment]
Wait for it, I'm cleaning this pull request.

**Comment by jmercouris** [comment]
Closing since other pull request was merged.

**Pull request closed without merging**
